### ISSUE TITLE
XH5For parallel output in cycle across nodes error

### ISSUE THREAD

**Issue by maps1996** [victorsndvg/XH5For#16] opened 2019-07-16 12:41 UTC
When I use xh5%WriteAttribute() in cycle cross nodes(more than 12 process), the result hdf5 file is empty, but its file size is not 0. If i do not use the subroutine in cycle. The hdf5 file is OK.Why it happens this situation? I would be really grateful if someone can help me.

**Comment by victorsndvg** [comment] 2019-07-16 14:11
Dear @maps1996 ,

Thanks for reporting. I would like to help you, but I need some more information to try to solve your issue.

It would be great if you can provide a reproducer (maybe I can use an already existing test/example?) and also the way you launch it. Even some info about HDF5 and mpi versions, parallel file system, etc.

Thanks again!

**Comment by maps1996** [comment] 2019-07-16 15:28
Dear @victorsndvg ,
Thanks for answering. I just put a test in my github which is just like your example in src. The test is compiled in my code. The version of my HDF5 is 1.10.4 and I use openmpi-2.1.1. Maybe I have some mistakes in using XH5For. Hope you can point it.

Thanks very much!

**Comment by victorsndvg** [comment] 2019-07-16 16:43
Thanks for the infor @maps1996,

I've access to an environment with HDF5 1.10.4 and openmpi-2.1.3 (slightly different, but let's see if I can reproduce) .

Anyway, what I don't understand is what `cycle cross nodes` means (sorry for my ignorance or my english). Can you explain it a little bit more? I only need technical details to understand how you launch the test that fails.

**Comment by maps1996** [comment] 2019-07-17 01:12
Sorry, It is my fault that I didn't explain properly. Cycle cross nodes means I run the test with 16 process.(Our server has 12cpus in one node). And when test has the do cycle, the result HDF5 file is wrong.

**Comment by victorsndvg** [comment] 2019-07-17 18:07
> Sorry, It is my fault that I didn't explain properly. Cycle cross nodes means I run the test with 16 process.(Our server has 12cpus in one node). And when test has the do cycle, the result HDF5 file is wrong.

do you mean something like mpiexec `-oversubscribe` flag?
Have you defined any communicator different to MPI_COMM_WORLD outside XH5For?

Now, at least, I've a starting point to do some checks.

Thanks for your patience!

**Comment by maps1996** [comment] 2019-07-18 06:42
The cycle is as follows. 

 do i=1,8
    xh5%WriteAttribute()
 enddo

When the code has this, it will get a wrong HDF5 file with 16 process.
I didn't use any communicator except MPI_COMM_WORLD.
My mpirun.sh is as follows:
-mpirun --mca btl_tcp_if_exclude "virbro,lo" -np 16 -machinefile ./.hostfile.txt ./fish

**Comment by victorsndvg** [comment] 2019-07-18 08:22
Dear @maps1996 ,

I'm not able to reproduce the issue ... 

First thing I cannot understand is how you can pass `-np 16` if your host only has 12cpus (maybe more cores?). If I do that, openmpi reports the following:
```
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 16 slots
that were requested by the application:
  bin/test

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```
Anyway, I can workaround this adding `-oversubscribe` flag to mpirun.

To see if all processes are doing the same thing, you can enable a couple of CMake flags an check stdout. Please, can you recompile your code with the following cmake flags:
```
-DXH5For_PRINT_IO_TIMES=ON -XH5For_FORCE_FLUSH=ON 
```
and run your test with the following openmpi flags:
```
mpirun ... --tag-output --output-filename output_dir ...
```
All output files should be equal except the times.

On the other hand, can you confirm that the following configuration is correct on your host?
```
--mca btl_tcp_if_exclude "virbro,lo" -machinefile ./.hostfile.txt
```
Can you try removing these flags? 

Can you dump (h5dump) the content of `fish_1.h5` HDF5 file an post the content?

Thanks in advance.

**Comment by maps1996** [comment] 2019-07-19 08:54
Dear @victorsndvg,
First, our server have 12cpus in one node. So when the -np is 16, that is what I said cross nodes.
Second, I added the flag -oversubcribe to mpirun. But the issue still exists. I will try to add CMake flags to see if all processes are doing the same thing.
Third, the mpirun.sh I wrote can run in our server. the --mca ... is used to disconnect internet port. I cannot remove these flags. 
Finally, I cannot dump the content of fish_1.h5.
Anyway, I really appreciate that you can answer my questions patiently.

**Comment by victorsndvg** [comment] 2019-07-19 09:03
Ok @maps1996 ,

let me know the output files content whenever you can try to add CMake flags.

As I cannot reproduce the issue, I started to think that the problem can be more closely related to your machine or the particular software versions used.

Another option to try to make it works is to change the write strategy from `XDMF_STRATEGY_CONTIGUOUS_HYPERSLAB` to `XDMF_STRATEGY_DATASET_PER_PROCESS`. `XDMF_STRATEGY_DATASET_PER_PROCESS` requires less coordination between process, it's less scalable, but enought for 16 process.

Let me know your results! :)

**Comment by maps1996** [comment] 2019-07-26 07:48
Dear @victorsndvg,
After adding CMake flags and recompiling the XH5For library and our program, the issue has been solved. Now we can open the XDMF file properly with paraview. Besides, both the two strategies can  write properly.

 I have one more question, in the mpirun.sh, I added the --tag-output --output-filename </apps/users/chfang/bin/out.txt>. But there is nothing in the out.txt. But I would not get right output hdf5 file without these flags.

Anyway, you really help me debug our program. Your code is really helpful. Thanks very much! Hope the XH5For get better! :)

**Comment by victorsndvg** [comment] 2019-07-26 11:27
Dear @maps1996 ,

thanks for your kind words and for using XH5For, reporting any issue and help me to improve the project. :smile: 

Nice to hear that things are working! great!

I think `--output-filename output` flag and value should create a DIRECTORY (`./output`) containing a file per process. Not a single file. If you remove this flags, then everything is shown on the screen.

I'm going to close the issue. Feel free to reopen it if needed.

Best,
Vícor

**Closed as completed by victorsndvg** 2019-07-26 11:27 UTC
